In [9]:
# import numpy
# create array x

import numpy as np

x = np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]])

print x

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [10]:
# print the shape of x

print x.shape

(4, 3)


In [12]:
# create a two dimensional array

twod_array = x.reshape(1,12)
twod_array

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [13]:
# print shape of 2d array
print twod_array.shape

(1, 12)


In [14]:
# reshape the array to 2 x 6
x.reshape(2,6)

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [15]:
# reshape the array to 1 x 12
x.reshape(1,12)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [16]:
# transpose the array
x.T

array([[ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [30]:
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [24]:
# indexing method 1
#Pulls the fist 2 items in the first 3 lists.

x[0:3, 0:2]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [27]:
# Indexing with Arrays of indices
"""This generates a three dimensional array. It pulls the 2nd and 4th row (1st and 3rd row place) of x into 
and array and generates a second array with 3rd row and 4th row.(3 and 4 place.)"""
y = np.array([[1,3],[2,3]])
x[y]

array([[[ 5,  6,  7],
        [11, 12, 13]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [46]:
#DELETE
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [44]:
# Indexing with Arrays of multi-dimensional indices
i = np.array([[0,1], [1,2]])                       
                
j = np.array([[2,1], [1,1]])
                
x[i,j]

array([[4, 6],
       [6, 9]])

In [64]:
# Indexing with Arrays of multi-dimensional indices in a list

r = np.array([i,j])
x[r]

array([[[[2, 3, 4],
         [5, 6, 7]],

        [[5, 6, 7],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [5, 6, 7]],

        [[5, 6, 7],
         [5, 6, 7]]]])

In [60]:
# indexing with arrays as a target to assign
#x[[2]] = 0
z = np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]])
z[[2,3],[0,1]] = 0
z

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 0,  9, 10],
       [11,  0, 13]])

In [62]:
# indexing with arrays as a target to assign in a list
q = np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]])
q[[2,3],[0,1]] = [90,91]
q

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [90,  9, 10],
       [11, 91, 13]])